apiVersion: qserv.lsst.org/v1alpha1
kind: Qserv
metadata:
  name: qserv
spec:
  czar:
    image: qserv/qserv:fe8b131e7
  dashboard:
    image: qserv/dashboard:41bf985
  worker:
    image: qserv/qserv:fe8b131e7
  replication:
      image: qserv/qserv:fe8b131e7
  xrootd:
    image: qserv/qserv:fe8b131e7
