sudo: required
language: go
dist: xenial

go:
  - 1.13.4

before_script:
  - if [ "$DOCKER_USERNAME" ]; then docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"; fi
  - ./install-operator-sdk.sh
  - git clone --depth 1 -b "k8s-v1.18.2" --single-branch https://github.com/k8s-school/kind-travis-ci.git
  - ./kind-travis-ci/k8s-create.sh -sc

script:
  - . ./env.sh
  - ./build.sh
  - kind load docker-image "$OP_IMAGE"
  - ./deploy.sh
  - kubectl apply -k manifests/base
  - ./tests/tools/wait-qserv-ready.sh
  - kubectl get all,endpoints,cm,pvc,pv,networkpolicies -o wide
  - ./tests/e2e/integration.sh 
