sudo: required
language: go
dist: xenial

go:
- 1.13.4

before_script:
  - if [ "$DOCKER_USERNAME" ]; then docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"; fi
  - ./install-operator-sdk.sh
  - git clone --depth 1 -b "k8s-1.18.2" --single-branch https://github.com/k8s-school/kind-travis-ci.git
  - ./kind-travis-ci/kind/k8s-create.sh -s

script:
  - ./build.sh
  - ./deploy.sh
  - ./wait-operator-ready.sh
  - kubectl apply -k base
  - ./wait-qserv-ready.sh 
  - kubectl get all,endpoints,cm,pvc,pv -o wide
  - ./run-integration-tests.sh
