apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/load-balancer-type: Internal
  labels:
    app: qserv
    component: czar
    instance: qserv
  name: test-ilb
  namespace: default
spec:
  ports:
  - name: proxy
    nodePort: 31086
    port: 4040
    protocol: TCP
    targetPort: 4040
  selector:
    app: qserv
    component: czar
    instance: qserv
  type: LoadBalancer
