apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/load-balancer-type: Internal
    cloud.google.com/neg: '{"ingress":true}'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"cloud.google.com/load-balancer-type":"Internal"},"labels":{"app":"qserv","component":"czar","instance":"qserv"},"name":"qserv-qserv-ilb","namespace":"default"},"spec":{"ports":[{"name":"proxy","port":4040,"protocol":"TCP","targetPort":4040}],"selector":{"app":"qserv","component":"czar","instance":"qserv"},"sessionAffinity":"None","type":"LoadBalancer"}}
  creationTimestamp: "2020-12-16T20:53:23Z"
  finalizers:
  - gke.networking.io/l4-ilb-v1
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: qserv
    component: czar
    instance: qserv
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:cloud.google.com/load-balancer-type: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:app: {}
          f:component: {}
          f:instance: {}
      f:spec:
        f:externalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":4040,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
          f:component: {}
          f:instance: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl
    operation: Update
    time: "2020-12-16T20:53:23Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .: {}
          v:"gke.networking.io/l4-ilb-v1": {}
          v:"service.kubernetes.io/load-balancer-cleanup": {}
      f:status:
        f:loadBalancer:
          f:ingress: {}
    manager: kube-controller-manager
    operation: Update
    time: "2020-12-16T20:54:13Z"
  name: qserv-qserv-ilb
  namespace: default
  resourceVersion: "111977"
  selfLink: /api/v1/namespaces/default/services/qserv-qserv-ilb
  uid: 0b5a63a3-5c3f-424e-b483-ff464453cd87
spec:
  clusterIP: 10.134.31.145
  externalTrafficPolicy: Cluster
  ports:
  - name: proxy
    nodePort: 31087
    port: 4040
    protocol: TCP
    targetPort: 4040
  selector:
    app: qserv
    component: czar
    instance: qserv
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 10.134.0.24
