apiVersion: qserv.lsst.org/v1alpha1
kind: Qserv
metadata:
  name: qserv
spec:
  storageClassName: "standard-rwo"
  storage: "1Gi"
  # replication:
  #    image: "qserv/replica:tools-w.2018.16-1345-gb9191ae-dirty"
  czar:
    storageClassName: "premium-rwo"
    storage: "2Gi"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: tier
              operator: In
              values:
              - czar
    proxyresources:
      requests:
        cpu: 24
  queryService:
      annotations:
        cloud.google.com/load-balancer-type: Internal
      type: LoadBalancer
  worker:
    storage: "3Gi"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: tier
              operator: In
              values:
              - worker
    replicas: 5
    replicationresources:
      limits:
        cpu: 14
