apiVersion: qserv.lsst.org/v1alpha1
kind: Qserv
metadata:
  name: qserv
spec:
  storageclass: "standard"
  storagecapacity: "1Gi"
  worker:
    replicas: 3
    image: "qserv/qserv:ad8405c"
  replication:
      image: "qserv/replica:tools-w.2018.16-1171-gcbabd53"
      dbimage: "mariadb:10.2.16"
  xrootd:
    replicas: 4
    image: "qserv/qserv:ad8405c"
