apiVersion: qserv.lsst.org/v1alpha1
kind: Qserv
metadata:
  name: qserv
spec:
  storage: "100Gi"
  czar:
    storage: "500Gi"
  queryService:
      loadBalancerIP: 10.136.0.49 
  worker:
    storage: "500Gi"
    replicas: 5
