apiVersion: qserv.lsst.org/v1alpha1
kind: Qserv
metadata:
  name: qserv
spec:
  storageclass: "qserv-local-storage"
  storagecapacity: "100Gi"
  # replication:
  #    image: "qserv/replica:tools-w.2018.16-1345-gb9191ae-dirty"
  worker:
    replicas: 20
